Vue.component('GeneralPics', require('./GeneralPics.vue').default)
Vue.component('MenuItem', require('./MenuItem.vue').default)
Vue.component('OrderItem', require('./OrderItem.vue').default)
Vue.component('ContactItem', require('./ContactItem.vue').default)
Vue.component('SliderItem', require('./SliderItem.vue').default)
